### ISSUE TITLE
this sentence is lost

### ISSUE THREAD

**Issue by ww2766** [gosbd/gosbd#12]
original := "Candidates tied to Tehreek-e-Insaf (PTI), the party of Imran Khan, won the most seats in Pakistan’s general election, despite a de facto ban on their campaign. Mr Khan is in prison on multiple charges, which he says are politically motivated. The Pakistan Muslim League-Nawaz (PML-N), which was widely expected to win, came second. PML-N is the party of Nawaz Sharif, Mr Khan’s arch-rival. It will form a coalition government with the Pakistan Peoples Party, which came third. Mr Khan’s supporters said the election had been rigged, which the PML-N denied. The head of the army claimed the poll had been “free and unhindered”."
	sent := "The Pakistan Muslim League-Nawaz (PML-N), which was widely expected to win, came second."
	segmenter := gosbd.NewSegmenter("en")
	sentences := segmenter.Segment(original)
	for _, sentence := range sentences {

		fmt.Println(sentence)
	}

the result :
[]string len: 6, cap: 8, ["Candidates tied to Tehreek-e-Insaf (PTI), the party of Imran Khan, won the most seats in Pakistan’s general election, despite a de facto ban on their campaign.","Mr Khan is in prison on multiple charges, which he says are politically motivated.","PML-N is the party of Nawaz Sharif, Mr Khan’s arch-rival.","It will form a coalition government with the Pakistan Peoples Party, which came third.","Mr Khan’s supporters said the election had been rigged, which the PML-N denied.","The head of the army claimed the poll had been “free and unhindered”."]
this sentence:sent := "The Pakistan Muslim League-Nawaz (PML-N), which was widely expected to win, came second." is lost.
please fix it. 3ks.

possable func (b BetweenPunctuation) punctuationBetweenParens(text string) string {
	return betweenParensRegex.ReplaceAllStringFunc(
		text, b.punctuationReplacer.ReplaceFunc(processor.PunctuationMatchTypeNone))
}

**Comment by ww2766** [comment]
error  deal at   "(PML-N)"

**Comment by yohamta** [comment]
@ww2766 The bug should be fixed now. Thanks a lot for reporting the issue.
